namespace: botmother

image:
  repository: registry.iprogrammer.uz/agentv2/botmother-agent
  tag: prod-7905e71
  pullPolicy: IfNotPresent

config:
  AGENT_MODEL: us.anthropic.claude-sonnet-4-5-20250929-v1:0
  AGENT_DATABASE_URL: sqlite:////app/data/agent_runs.db
  AGENT_REDIS_URL: redis://agentv2-redis:6379/0
  AGENT_CORS_ORIGINS: https://botspace.uz,https://botmother.uz
  IS_OLLAMA: "false"

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: botlarnionasi.jscorp.uz
      paths:
        - path: /api/agentv2(/|$)(.*)
          pathType: ImplementationSpecific
    - host: api.botmother.uz
      paths:
        - path: /api/agentv2(/|$)(.*)
          pathType: ImplementationSpecific
    - host: api.botspace.uz
      paths:
        - path: /api/agentv2(/|$)(.*)
          pathType: ImplementationSpecific
