from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class FieldCapability:
    dsl_name: str
    export_path: str
    import_paths: tuple[str, ...] = ()
    required: bool = False
    description: str | None = None

    def import_candidates(self) -> tuple[str, ...]:
        return self.import_paths or (self.export_path,)


@dataclass(frozen=True)
class NodeCapability:
    kind: str
    node_type: str
    fields: tuple[FieldCapability, ...] = ()
    is_trigger: bool = False
    button_target_edges: bool = False
    selected_message_target: bool = False
    output_routes: bool = False
    route_handles: tuple[str, ...] = ()
    notes: tuple[str, ...] = ()
    aliases: tuple[str, ...] = ()

    def field_names(self) -> list[str]:
        return [field.dsl_name for field in self.fields]

    def required_fields(self) -> list[str]:
        return [field.dsl_name for field in self.fields if field.required]


def field(
    dsl_name: str,
    export_path: str,
    *import_paths: str,
    required: bool = False,
    description: str | None = None,
) -> FieldCapability:
    return FieldCapability(
        dsl_name=dsl_name,
        export_path=export_path,
        import_paths=tuple(import_paths),
        required=required,
        description=description,
    )


def capability(
    kind: str,
    node_type: str,
    *fields: FieldCapability,
    is_trigger: bool = False,
    button_target_edges: bool = False,
    selected_message_target: bool = False,
    output_routes: bool = False,
    route_handles: tuple[str, ...] = (),
    notes: tuple[str, ...] = (),
    aliases: tuple[str, ...] = (),
) -> NodeCapability:
    return NodeCapability(
        kind=kind,
        node_type=node_type,
        fields=fields,
        is_trigger=is_trigger,
        button_target_edges=button_target_edges,
        selected_message_target=selected_message_target,
        output_routes=output_routes,
        route_handles=route_handles,
        notes=notes,
        aliases=aliases,
    )


COMMON_MESSAGE_FIELDS = (
    field("keyboard", "keyboard"),
    field("recipients", "recipients"),
    field("disable_notification", "disableNotification"),
    field("dynamic_messages", "dynamicMessages"),
)


CATALOG: tuple[NodeCapability, ...] = (
    capability(
        "command_trigger",
        "CommandTriggerNode",
        field("command", "command", required=True),
        field("global_flag", "global"),
        field("with_args", "withArgs"),
        is_trigger=True,
    ),
    capability(
        "message_trigger",
        "MessageTriggerNode",
        field("message_type", "type"),
        field("filter", "filter"),
        field("value", "context.value"),
        field("state", "state"),
        is_trigger=True,
    ),
    capability(
        "callback_query_trigger",
        "CallbackQueryTriggerNode",
        field("filter", "filter"),
        field("value", "context.value"),
        field("state", "state"),
        is_trigger=True,
    ),
    capability(
        "callback_button_trigger",
        "CallbackButtonTriggerNode",
        field("selected_callbacks", "selectedCallbacks"),
        field("state", "state"),
        is_trigger=True,
    ),
    capability(
        "reply_button_trigger",
        "ReplyButtonTriggerNode",
        field("buttons", "selectedButtons"),
        field("state", "state"),
        is_trigger=True,
    ),
    capability(
        "external_webhook_trigger",
        "ExternalWebhookTriggerNode",
        field("provider", "provider", required=True),
        is_trigger=True,
        notes=("Matches POST /custom-webhook/{provider}[/{chat_id}] requests.",),
    ),
    capability(
        "cron_trigger",
        "CronTriggerNode",
        field("schedule", "schedule", required=True),
        field("enabled", "enabled"),
        field("target_chat_ids", "targetChatIds"),
        is_trigger=True,
        notes=("Cron trigger must be a root trigger with no incoming edges.",),
    ),
    capability(
        "send_text",
        "SendTextMessageNode",
        field("text", "messageText", "messageText", "newText", required=True),
        field("parse_mode", "parseMode"),
        field("disable_web_page_preview", "disableWebPagePreview"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_photo",
        "SendPhotoNode",
        field("photo_source_type", "photoSourceType"),
        field("photo_file_id", "photoFileId"),
        field("photo_url", "photoUrl"),
        field("uploaded_file_uuid", "uploadedFileUuid"),
        field("caption", "caption"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_video",
        "SendVideoNode",
        field("video_source_type", "videoSourceType"),
        field("video_file_id", "videoFileId"),
        field("video_url", "videoUrl"),
        field("uploaded_file_uuid", "uploadedFileUuid"),
        field("caption", "caption"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_audio",
        "SendAudioNode",
        field("audio_source_type", "audioSourceType"),
        field("audio_file_id", "audioFileId"),
        field("audio_url", "audioUrl"),
        field("uploaded_file_uuid", "uploadedFileUuid"),
        field("caption", "caption"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_file",
        "SendFileNode",
        field("file_source_type", "fileSourceType"),
        field("file_id", "fileId"),
        field("file_url", "fileUrl"),
        field("uploaded_file_uuid", "uploadedFileUuid"),
        field("caption", "caption"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_animation",
        "SendAnimationNode",
        field("animation_source_type", "animationSourceType"),
        field("animation_file_id", "animationFileId"),
        field("animation_url", "animationUrl"),
        field("uploaded_file_uuid", "uploadedFileUuid"),
        field("caption", "caption"),
        field("parse_mode", "parseMode"),
        field("duration", "duration"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_voice",
        "SendVoiceNode",
        field("voice_source_type", "voiceSourceType"),
        field("voice_file_id", "voiceFileId"),
        field("voice_url", "voiceUrl"),
        field("uploaded_file_uuid", "uploadedFileUuid"),
        field("caption", "caption"),
        field("parse_mode", "parseMode"),
        field("duration", "duration"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_video_note",
        "SendVideoNoteNode",
        field("video_note_source_type", "videoNoteSourceType"),
        field("video_note_file_id", "videoNoteFileId"),
        field("video_note_url", "videoNoteUrl"),
        field("uploaded_file_uuid", "uploadedFileUuid"),
        field("duration", "duration"),
        field("length", "length"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_location",
        "SendLocationNode",
        field("latitude", "latitude"),
        field("longitude", "longitude"),
        field("live_period", "livePeriod"),
        field("heading", "heading"),
        field("horizontal_accuracy", "horizontalAccuracy"),
        field("proximity_alert_radius", "proximityAlertRadius"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_contact",
        "SendContactNode",
        field("phone_number", "phoneNumber"),
        field("first_name", "firstName"),
        field("last_name", "lastName"),
        field("v_card", "vCard"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_poll",
        "SendPollNode",
        field("question", "question"),
        field("options", "options"),
        field("type", "type"),
        field("is_anonymous", "isAnonymous"),
        field("allows_multiple_answers", "allowsMultipleAnswers"),
        field("correct_option_id", "correctOptionID"),
        field("explanation", "explanation"),
        field("explanation_parse_mode", "explanationParseMode"),
        field("open_period", "openPeriod"),
        field("is_closed", "isClosed"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_sticker",
        "SendStickerNode",
        field("sticker_source_type", "stickerSourceType"),
        field("sticker_file_id", "stickerFileId"),
        field("sticker_url", "stickerUrl"),
        field("uploaded_file_uuid", "uploadedFileUuid"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_media_group",
        "SendMediaGroupNode",
        field("media_items", "mediaItems", required=True),
        field("recipients", "recipients"),
        field("disable_notification", "disableNotification"),
        field("dynamic_messages", "dynamicMessages"),
    ),
    capability(
        "send_venue",
        "SendVenueNode",
        field("latitude", "latitude"),
        field("longitude", "longitude"),
        field("title", "title"),
        field("address", "address"),
        field("foursquare_id", "foursquareId"),
        field("foursquare_type", "foursquareType"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "send_dice",
        "SendDiceNode",
        field("emoji", "emoji"),
        *COMMON_MESSAGE_FIELDS,
        button_target_edges=True,
    ),
    capability(
        "edit_message",
        "EditMessageNode",
        field("text", "messageText", "messageText", "newText"),
        field("parse_mode", "parseMode"),
        field("keyboard", "keyboard"),
        field("disable_web_page_preview", "disableWebPagePreview"),
        field("dynamic_messages", "dynamicMessages"),
        field("target_node_id", "targetNodeId"),
        field("message_id_source", "messageIdSource"),
        button_target_edges=True,
        selected_message_target=True,
    ),
    capability(
        "edit_or_send_text",
        "EditOrSendMessageNode",
        field("text", "messageText", "messageText", "dynamicMessageText"),
        field("parse_mode", "parseMode"),
        field("keyboard", "keyboard"),
        field("recipients", "recipients"),
        field("disable_web_page_preview", "disableWebPagePreview"),
        field("disable_notification", "disableNotification"),
        field("dynamic_messages", "dynamicMessages"),
        button_target_edges=True,
        aliases=("edit_or_send_message",),
    ),
    capability(
        "delete_message",
        "DeleteMessageNode",
        field("delete_from_context", "deleteFromContext"),
        field("target_node_id", "targetNodeId"),
        selected_message_target=True,
    ),
    capability(
        "forward_message",
        "ForwardMessageNode",
        field("recipients", "recipients"),
        field("disable_notification", "disableNotification"),
    ),
    capability(
        "copy_message",
        "CopyMessageNode",
        field("from_chat_id", "fromChatId"),
        field("message_id", "messageId"),
        field("caption", "caption"),
        field("parse_mode", "parseMode"),
        field("keyboard", "keyboard"),
        field("recipients", "recipients"),
        field("disable_notification", "disableNotification"),
        button_target_edges=True,
    ),
    capability(
        "pin_message",
        "PinMessageNode",
        field("message_id", "messageId"),
        field("disable_notification", "disableNotification"),
    ),
    capability(
        "unpin_message",
        "UnpinMessageNode",
        field("message_id", "messageId"),
        field("unpin_all", "unpinAll"),
    ),
    capability("unpin_all_messages", "UnpinAllMessagesNode"),
    capability("chat_action", "ChatActionNode", field("action", "action")),
    capability(
        "callback_query_answer",
        "CallbackQueryAnswerNode",
        field("callback_query_id", "callbackQueryId"),
        field("text", "text"),
        field("show_alert", "showAlert"),
        field("url", "url"),
        field("cache_time", "cacheTime"),
    ),
    capability(
        "answer_inline_query",
        "AnswerInlineQueryNode",
        field("results", "results"),
        field("cache_time", "cacheTime"),
        field("is_personal", "isPersonal"),
    ),
    capability(
        "check_membership",
        "CheckMembershipNode",
        field("channels", "channels"),
        field("channel_id", "channelId"),
        field("channel_username", "channelUsername"),
        route_handles=("is-member", "not-member"),
    ),
    capability(
        "if_condition",
        "IfConditionNode",
        field("branches", "branches"),
        field("conditions", "conditions"),
        field("operator", "operator"),
        route_handles=("true", "false", "next", "branch_{index}"),
    ),
    capability(
        "else_if",
        "ElseIfNode",
        field("conditions", "conditions"),
        field("operator", "operator"),
        route_handles=("true", "next"),
    ),
    capability(
        "else",
        "ElseNode",
        route_handles=("true",),
    ),
    capability(
        "delay",
        "DelayNode",
        field("delay", "delay"),
        field("delay_seconds", "delaySeconds"),
        field("duration", "duration"),
    ),
    capability(
        "scheduler",
        "SchedulerNode",
        field("scheduled_date_time", "scheduledDateTime"),
        field("date", "date"),
        field("time", "time"),
        field("timestamp", "timestamp"),
        field("delay_seconds", "delaySeconds"),
        field("year", "year"),
        field("month", "month"),
        field("day", "day"),
        field("hour", "hour"),
        field("minute", "minute"),
        field("second", "second"),
        field("target_node_id", "targetNodeId", required=True),
        field("recipients", "recipients"),
    ),
    capability(
        "random",
        "RandomNode",
        field("options", "options"),
        route_handles=("option_{index}",),
    ),
    capability(
        "variable",
        "VariableNode",
        field("operation", "operation"),
        field("variable_name", "variableName"),
        field("value", "value"),
        field("increment", "increment"),
        field("decrement", "decrement"),
        field("json_string", "jsonString"),
    ),
    capability(
        "for_loop",
        "ForLoopNode",
        field("data_key", "dataKey"),
        field("filters", "filters"),
        field("item_variable", "itemVariable"),
        field("loop_id", "loopID"),
        field("loop_mode", "loopMode"),
        field("range_start", "rangeStart"),
        field("range_end", "rangeEnd"),
        field("range_step", "rangeStep"),
        field("timeout", "timeout"),
        route_handles=("loop-body", "no-items"),
    ),
    capability(
        "for_loop_continue",
        "ForLoopContinueNode",
        field("loop_id", "loopID"),
        route_handles=("loop-continue", "loop-done"),
    ),
    capability(
        "http_request",
        "HTTPRequestNode",
        field("url", "url", required=True),
        field("method", "method"),
        field("headers", "headers"),
        field("body", "body"),
        field("response_variable", "responseVariable"),
        field("store_headers", "storeHeaders"),
        field("timeout", "timeout"),
    ),
    capability("send_to_admin", "SendToAdminNode"),
    capability(
        "custom_code",
        "CustomCodeNode",
        field("code", "jsCode", "jsCode", "code"),
        field("lua_code", "luaCode"),
        field("timeout", "timeout"),
        output_routes=True,
    ),
    capability(
        "state",
        "StateNode",
        field("state_key", "key"),
        field("state_type", "type"),
        field("custom_type", "customType"),
        field("collection_key", "collectionKey"),
        field("field_name", "fieldName"),
        field("value", "value"),
        field("index", "index"),
        field("context_key", "contextKey"),
    ),
    capability(
        "collection",
        "CollectionNode",
        field("collection_name", "collection_name"),
        field("field_mappings", "fieldMappings"),
    ),
    capability(
        "load_collection_item",
        "LoadCollectionItemNode",
        field("collection_name", "collection.name"),
        field("context_key", "contextKey"),
        field("filters", "filters"),
        route_handles=("found", "not_found"),
    ),
    capability(
        "load_collection_list",
        "LoadCollectionListNode",
        field("collection_name", "collection.name"),
        field("context_key", "contextKey"),
        field("filters", "filters"),
        field("limit", "limit"),
        field("skip", "skip"),
    ),
    capability(
        "update_collection",
        "UpdateCollectionNode",
        field("collection_name", "collection_name"),
        field("filters", "filters"),
        field("field_mappings", "fieldMappings"),
    ),
    capability(
        "delete_collection",
        "DeleteCollectionNode",
        field("collection_name", "collection_name"),
        field("filters", "filters"),
    ),
    capability(
        "download",
        "DownloadNode",
        field("key", "key"),
        field("uuid", "uuid"),
        field("file", "file"),
        field("filetype", "filetype"),
        field("filesize", "filesize"),
    ),
    capability(
        "cron", "CronNode", field("schedule", "schedule"), field("enabled", "enabled")
    ),
    capability(
        "subflow",
        "SubFlowNode",
        field("flow", "flow"),
        field("slug", "slug"),
        field("params", "params"),
        output_routes=True,
        notes=("Routes with `on` are emitted as output-{name} handles.",),
    ),
    capability("subflow_exit", "SubFlowExitNode", field("output", "output")),
)


CAPABILITY_BY_KIND = {cap.kind: cap for cap in CATALOG}
for cap in CATALOG:
    for alias in cap.aliases:
        CAPABILITY_BY_KIND[alias] = cap

CAPABILITY_BY_NODE_TYPE = {cap.node_type: cap for cap in CATALOG}
KIND_TO_NODE_TYPE = {cap.kind: cap.node_type for cap in CATALOG}
NODE_TYPE_TO_KIND = {cap.node_type: cap.kind for cap in CATALOG}
TRIGGER_KINDS = {cap.kind for cap in CATALOG if cap.is_trigger}
TRIGGER_NODE_TYPES = {cap.node_type for cap in CATALOG if cap.is_trigger}


def native_kinds() -> list[str]:
    return [cap.kind for cap in CATALOG]


def runtime_node_types() -> list[str]:
    return [cap.node_type for cap in CATALOG]


def get_capability_for_kind(kind: str) -> NodeCapability | None:
    return CAPABILITY_BY_KIND.get(kind)


def get_capability_for_node_type(node_type: str) -> NodeCapability | None:
    return CAPABILITY_BY_NODE_TYPE.get(node_type)


def describe_kind(kind: str) -> dict[str, object] | None:
    capability = get_capability_for_kind(kind)
    if capability is None:
        return None
    return {
        "kind": capability.kind,
        "runtime_node_type": capability.node_type,
        "purpose": describe_kind_purpose(capability.kind),
        "is_trigger": capability.is_trigger,
        "fields": [
            {
                "name": field.dsl_name,
                "runtime_key": field.export_path,
                "required": field.required,
                "description": describe_field(field),
                "ai_prompt": describe_field_for_ai(field),
                "example": example_for_field(field.dsl_name),
            }
            for field in capability.fields
        ],
        "allowed_fields": capability.field_names(),
        "required_fields": capability.required_fields(),
        "route_handles": list(capability.route_handles),
        "button_target_edges": capability.button_target_edges,
        "selected_message_target": capability.selected_message_target,
        "output_routes": capability.output_routes,
        "aliases": list(capability.aliases),
        "notes": list(capability.notes),
    }


def describe_kind_purpose(kind: str) -> str:
    purposes = {
        "command_trigger": "Telegram command kelganda flowni boshlaydi, masalan `/start`.",
        "message_trigger": "Foydalanuvchidan kelgan xabarni kutadi va mos kelsa flow davom etadi.",
        "callback_query_trigger": "Maxsus callback oqimini boshlaydi yoki waiting trigger sifatida davom ettiradi; static keyboard menu buttonlari uchun global trigger yaratmang, button `next` edge ishlating.",
        "callback_button_trigger": "Maxsus tanlangan callback qiymatlari bo'yicha waiting/root trigger; static inline menu buttonlari uchun global trigger yaratmang, button `next` edge ishlating.",
        "reply_button_trigger": "Reply keyboard tugmasi bosilganda flow boshlaydi yoki davom ettiradi.",
        "external_webhook_trigger": "Tashqi webhook request kelganda flowni boshlaydi.",
        "cron_trigger": "Cron jadvali bo'yicha flowni avtomatik boshlaydi.",
        "send_text": "Foydalanuvchiga matnli Telegram xabar yuboradi.",
        "send_photo": "Foydalanuvchiga rasm yuboradi.",
        "send_video": "Foydalanuvchiga video yuboradi.",
        "send_audio": "Foydalanuvchiga audio fayl yuboradi.",
        "send_file": "Foydalanuvchiga hujjat yoki fayl yuboradi.",
        "send_animation": "Foydalanuvchiga GIF/animation yuboradi.",
        "send_voice": "Foydalanuvchiga voice message yuboradi.",
        "send_video_note": "Foydalanuvchiga dumaloq video note yuboradi.",
        "send_location": "Foydalanuvchiga geografik lokatsiya yuboradi.",
        "send_contact": "Foydalanuvchiga kontakt ma'lumotini yuboradi.",
        "send_poll": "Foydalanuvchiga poll yoki quiz yuboradi.",
        "send_sticker": "Foydalanuvchiga sticker yuboradi.",
        "send_media_group": "Foydalanuvchiga bir nechta media elementni album sifatida yuboradi.",
        "send_venue": "Foydalanuvchiga venue/manzil kartasini yuboradi.",
        "send_dice": "Foydalanuvchiga Telegram dice animatsiyasini yuboradi.",
        "edit_message": "Oldin yuborilgan xabar matni yoki keyboardini tahrirlaydi.",
        "edit_or_send_text": "Xabarni tahrirlaydi, tahrirlash imkoni bo'lmasa yangi matnli xabar yuboradi. inline buttonlar bilan ishlaganda asosan ishlatiladi inline tugma bosilganda xabarni edit qiladi chalkashlikni oldini oladi",
        "delete_message": "Oldin yuborilgan yoki kontekstdagi xabarni o'chiradi.",
        "forward_message": "Boshqa chat/xabardan forward qiladi.",
        "copy_message": "Boshqa chat/xabardan nusxa olib yuboradi.",
        "pin_message": "Chatdagi xabarni pin qiladi.",
        "unpin_message": "Chatdagi pin qilingan xabarni olib tashlaydi.",
        "unpin_all_messages": "Chatdagi barcha pin qilingan xabarlarni olib tashlaydi.",
        "chat_action": "Telegram chat action ko'rsatadi, masalan typing yoki upload_photo.",
        "callback_query_answer": "Callback button bosilgandan keyin Telegram callback javobini yuboradi.",
        "answer_inline_query": "Inline query uchun natijalar qaytaradi.",
        "check_membership": "Foydalanuvchi kanal/guruh a'zosi ekanini tekshiradi.",
        "if_condition": "Shartlarni tekshiradi va natijaga qarab branchlarga yo'naltiradi.",
        "else_if": "If chain ichidagi qo'shimcha shart branchini tekshiradi.",
        "else": "If chain ichidagi default/fallback branch vazifasini bajaradi.",
        "delay": "Flow bajarilishini vaqtincha kechiktiradi.",
        "scheduler": "Kelajak vaqtga xabar yoki keyingi action bajarilishini rejalashtiradi.",
        "random": "Tasodifiy branch tanlab flow yo'nalishini o'zgartiradi.",
        "variable": "Kontekst o'zgaruvchisini yaratadi, o'zgartiradi yoki hisoblaydi.",
        "for_loop": "Ro'yxat yoki range bo'yicha takroriy bajarish loopini boshlaydi.",
        "for_loop_continue": "Loopni keyingi elementga o'tkazadi yoki tugatadi.",
        "http_request": "Tashqi HTTP API chaqiradi va javobni kontekstga saqlaydi.",
        "send_to_admin": "Adminlarga xabar yuborish uchun ishlatiladi.",
        "custom_code": "JavaScript kodini bajarib murakkab mantiq yoki integratsiya qiladi.",
        "state": "Foydalanuvchi javobi yoki qiymatni state/context ichiga saqlaydi.",
        "collection": "Collectionga yangi ma'lumot yozadi.",
        "load_collection_item": "Collectiondan bitta mos elementni yuklaydi.",
        "load_collection_list": "Collectiondan mos elementlar ro'yxatini yuklaydi.",
        "update_collection": "Collectiondagi mavjud elementlarni yangilaydi.",
        "delete_collection": "Collectiondagi mos elementlarni o'chiradi.",
        "download": "Faylni yuklab olish yoki fayl metadata bilan ishlash uchun ishlatiladi.",
        "cron": "Cron asosidagi scheduled action node sifatida ishlaydi.",
        "subflow": "Boshqa subflowni chaqiradi va parametrlar uzatadi.",
        "subflow_exit": "Subflowdan nomlangan output bilan chiqadi.",
    }
    return purposes.get(kind, f"`{kind}` node turi uchun native DSL capability.")


def describe_field(field: FieldCapability) -> str:
    if field.description:
        return field.description

    overrides = {
        "command": "Telegram command that triggers the flow, for example `/start`.",
        "global_flag": "If true, this trigger fires globally and can reset the current flow.",
        "with_args": "If true, the trigger also captures command arguments after the command text.",
        "message_type": "Type of incoming Telegram message to match, such as `text`, `photo`, or `any`.",
        "filter": "Additional trigger filter rule used by the runtime to narrow matching updates.",
        "value": "Filter value or comparison value used together with the trigger/filter configuration.",
        "state": "State capture or waiting-state configuration saved into flow context.",
        "selected_callbacks": "Allowed callback data values that should match this callback button trigger.",
        "buttons": "Reply button definitions or selected reply buttons used by this trigger.",
        "provider": "Webhook provider name matched against `/custom-webhook/{provider}`.",
        "schedule": "Cron expression or scheduling string used by cron-based nodes.",
        "enabled": "Turns the cron/scheduled behavior on or off.",
        "target_chat_ids": "List of Telegram chat IDs that cron jobs should run for.",
        "text": "Main text content sent or edited in the message.",
        "parse_mode": "Telegram parse mode for rich text, usually `HTML` or `Markdown`.",
        "disable_web_page_preview": "If true, Telegram link previews are disabled for the text message.",
        "keyboard": "Inline or reply keyboard configuration attached to the outgoing message.",
        "recipients": "Recipient override config. If omitted, the current chat is used.",
        "disable_notification": "If true, the message is sent silently without Telegram notification sound.",
        "dynamic_messages": "Dynamic message blocks processed before the node sends its final output.",
        "target_node_id": "Runtime target node reference, usually pointing to another sent message node.",
        "message_id_source": "How the message ID should be resolved when editing an existing message.",
        "message_id": "Explicit Telegram message ID used by pin/copy/unpin style nodes.",
        "delete_from_context": "If true, delete the message from callback context instead of using a target node.",
        "from_chat_id": "Source chat ID used when copying a message from another chat.",
        "unpin_all": "If true, unpins all pinned messages instead of a single message.",
        "action": "Telegram chat action such as `typing`, `upload_photo`, or `record_video`.",
        "state_key": "Context/state key that this node reads or writes.",
        "state_type": "State storage mode used by the state node.",
        "custom_type": "Custom data type hint used by state handling.",
        "collection_key": "Collection-related key used by state or collection nodes.",
        "field_name": "Single field name targeted inside a collection or state payload.",
        "collection_name": "Mongo collection name used by collection nodes.",
        "context_key": "Context variable name where loaded data should be stored.",
        "filters": "Filter conditions used for collection queries or loop data selection.",
        "limit": "Maximum number of items to load from a collection query.",
        "skip": "How many items to skip before collecting results.",
        "field_mappings": "Field mapping object describing how input values are written into collection documents.",
        "operation": "Variable operation to perform, such as `set`, `increment`, or `decrement`.",
        "variable_name": "Context variable name affected by the variable node.",
        "increment": "Numeric increment amount for increment operations.",
        "decrement": "Numeric decrement amount for decrement operations.",
        "conditions": "Condition list evaluated by logic nodes.",
        "operator": "Logical operator joining conditions, typically `AND` or `OR`.",
        "branches": "Structured branch definitions for multi-branch logic nodes.",
        "code": "JavaScript source code executed by the custom code node.",
        "lua_code": "Lua source code field preserved for compatibility if present in runtime data.",
        "timeout": "Execution timeout in seconds or milliseconds depending on the runtime node.",
        "photo_source_type": "How the photo is provided: URL, Telegram file ID, or uploaded file UUID.",
        "photo_file_id": "Telegram file ID of the photo to send.",
        "photo_url": "Public URL of the photo to send.",
        "video_source_type": "How the video is provided: URL, Telegram file ID, or uploaded file UUID.",
        "video_file_id": "Telegram file ID of the video to send.",
        "video_url": "Public URL of the video to send.",
        "audio_source_type": "How the audio is provided: URL, Telegram file ID, or uploaded file UUID.",
        "audio_file_id": "Telegram file ID of the audio to send.",
        "audio_url": "Public URL of the audio to send.",
        "file_source_type": "How the document/file is provided: URL, Telegram file ID, or uploaded file UUID.",
        "file_id": "Telegram file ID for a generic file/document node.",
        "file_url": "Public URL of the generic file/document to send.",
        "animation_source_type": "How the animation is provided: URL, Telegram file ID, or uploaded file UUID.",
        "animation_file_id": "Telegram file ID of the animation to send.",
        "animation_url": "Public URL of the animation to send.",
        "voice_source_type": "How the voice file is provided: URL, Telegram file ID, or uploaded file UUID.",
        "voice_file_id": "Telegram file ID of the voice message to send.",
        "voice_url": "Public URL of the voice message to send.",
        "video_note_source_type": "How the video note is provided: URL, Telegram file ID, or uploaded file UUID.",
        "video_note_file_id": "Telegram file ID of the video note to send.",
        "video_note_url": "Public URL of the video note to send.",
        "sticker_source_type": "How the sticker is provided: URL, Telegram file ID, or uploaded file UUID.",
        "sticker_file_id": "Telegram file ID of the sticker to send.",
        "sticker_url": "Public URL of the sticker to send.",
        "uploaded_file_uuid": "Uploaded-file UUID returned by Botmother upload flow.",
        "caption": "Caption text attached to a media message.",
        "duration": "Duration value used by media or delay-like nodes.",
        "length": "Displayed length/diameter for video note style messages.",
        "latitude": "Latitude coordinate used by location or venue nodes.",
        "longitude": "Longitude coordinate used by location or venue nodes.",
        "live_period": "Telegram live location period in seconds.",
        "heading": "Heading used for live location updates.",
        "horizontal_accuracy": "Accuracy radius for live location updates.",
        "proximity_alert_radius": "Proximity alert radius for live location updates.",
        "phone_number": "Phone number sent by contact nodes.",
        "first_name": "First name used in contact payloads.",
        "last_name": "Last name used in contact payloads.",
        "v_card": "Optional vCard payload sent together with a contact.",
        "question": "Poll question text shown to the user.",
        "options": "Option list for polls or random-selection nodes.",
        "is_anonymous": "Whether the poll should hide voter identities.",
        "allows_multiple_answers": "Whether users may choose multiple poll options.",
        "correct_option_id": "Correct option index for quiz-type polls.",
        "explanation": "Explanation text shown after answering a quiz poll.",
        "explanation_parse_mode": "Parse mode applied to the poll explanation text.",
        "open_period": "Auto-close period for polls, in seconds.",
        "is_closed": "If true, sends the poll already closed.",
        "media_items": "Media group item list; each item describes type, source, and optional caption.",
        "address": "Venue address text.",
        "foursquare_id": "Foursquare venue ID if available.",
        "foursquare_type": "Foursquare venue category/type if available.",
        "emoji": "Emoji used by dice nodes, for example `🎲` or `🎯`.",
        "callback_query_id": "Explicit callback query ID, usually only needed when context does not already contain it.",
        "show_alert": "If true, Telegram shows the callback answer as a popup alert.",
        "url": "URL opened or requested by the node, depending on node type.",
        "cache_time": "Telegram callback/inline cache time in seconds.",
        "results": "Inline query result objects returned by AnswerInlineQuery nodes.",
        "is_personal": "If true, inline query results are marked as personal to the user.",
        "channels": "Channel list checked by membership validation nodes.",
        "channel_id": "Single legacy channel ID used by membership checks.",
        "channel_username": "Single legacy channel username used by membership checks.",
        "delay": "Delay string or value used by DelayNode.",
        "delay_seconds": "Delay duration in seconds.",
        "scheduled_date_time": "Absolute scheduled datetime string for SchedulerNode.",
        "date": "Date portion used by SchedulerNode.",
        "time": "Time portion used by SchedulerNode.",
        "timestamp": "Unix timestamp used for scheduling.",
        "year": "Year component used by SchedulerNode.",
        "month": "Month component used by SchedulerNode.",
        "day": "Day component used by SchedulerNode.",
        "hour": "Hour component used by SchedulerNode.",
        "minute": "Minute component used by SchedulerNode.",
        "second": "Second component used by SchedulerNode.",
        "json_string": "Serialized JSON string used by variable operations when needed.",
        "data_key": "Context key containing loop input data.",
        "item_variable": "Loop variable name exposed for each item iteration.",
        "loop_id": "Loop identifier shared between loop start and continue nodes.",
        "loop_mode": "Loop mode such as range-based or data-based iteration.",
        "range_start": "Start value for numeric range loops.",
        "range_end": "End value for numeric range loops.",
        "range_step": "Step size for numeric range loops.",
        "headers": "HTTP header map sent with HTTP requests.",
        "body": "HTTP request body payload.",
        "response_variable": "Context variable name where the HTTP response body should be stored.",
        "store_headers": "If true, response headers are also stored in context.",
        "output": "Named subflow exit output emitted by SubFlowExitNode.",
        "flow": "Inline embedded subflow runtime JSON used by SubFlowNode.",
        "slug": "Plugin slug used to resolve a subflow from the plugin service.",
        "params": "Parameter object injected into subflow context as `param_*` keys.",
        "key": "Download/cache key used by DownloadNode.",
        "uuid": "UUID used by download/file reference nodes.",
        "file": "File name or file reference used by DownloadNode.",
        "filetype": "Detected or forced file type used by DownloadNode.",
        "filesize": "Detected file size metadata used by DownloadNode.",
    }
    if field.dsl_name in overrides:
        return overrides[field.dsl_name]

    return f"`{field.dsl_name}` maps to runtime field `{field.export_path}`."


def describe_field_for_ai(field: FieldCapability) -> str:
    return (
        f"Use `{field.dsl_name}` when you need {describe_field(field).rstrip('.')}. "
        f"Put it directly inside the StepSpec for the selected kind. "
        f"It compiles to runtime data key `{field.export_path}`. "
        f"Example: `{field.dsl_name}: {example_for_field(field.dsl_name)}`."
    )


def example_for_field(name: str) -> str:
    examples = {
        "action": "typing",
        "address": "Amir Temur street, Tashkent",
        "allows_multiple_answers": "false",
        "animation_file_id": "CgACAgQAAxkBA...",
        "animation_source_type": "url",
        "animation_url": "https://example.com/animation.gif",
        "audio_file_id": "CQACAgQAAxkBA...",
        "audio_source_type": "url",
        "audio_url": "https://example.com/audio.mp3",
        "body": '{"status":"paid"}',
        "branches": '[{"type":"if","conditions":[...]},{"type":"else"}]',
        "buttons": '[{"text":"Menu"}]',
        "cache_time": "60",
        "callback_query_id": "{{callback_query.id}}",
        "caption": "Mana video: {{title}}",
        "channel_id": "-1001234567890",
        "channel_username": "@my_channel",
        "channels": '[{"value":"@my_channel"}]',
        "code": "exit('success')",
        "collection_key": "movies",
        "collection_name": "movies",
        "command": "/start",
        "conditions": '[{"left":"{{state_code}}","operator":"==","right":"123"}]',
        "context_key": "movie",
        "correct_option_id": "0",
        "custom_type": "string",
        "data_key": "collection_movies",
        "date": "2026-04-21",
        "day": "21",
        "decrement": "1",
        "delay": "5s",
        "delay_seconds": "5",
        "delete_from_context": "true",
        "disable_notification": "true",
        "disable_web_page_preview": "true",
        "duration": "10",
        "dynamic_messages": '[{"key":"movie","text":"{{title}}"}]',
        "emoji": "🎲",
        "enabled": "true",
        "explanation": "To'g'ri javob A edi",
        "explanation_parse_mode": "HTML",
        "field_mappings": '{"title":"{{state_title}}"}',
        "field_name": "title",
        "file": "{{message.document}}",
        "file_id": "BQACAgQAAxkBA...",
        "file_source_type": "url",
        "file_url": "https://example.com/file.pdf",
        "filesize": "1048576",
        "filetype": "video",
        "filter": "equals",
        "filters": '[{"field":"code","operator":"==","value":"{{state_code}}"}]',
        "first_name": "Ali",
        "flow": '{"nodes":[...],"edges":[...]}',
        "foursquare_id": "4e7...",
        "foursquare_type": "food/restaurant",
        "from_chat_id": "-1001234567890",
        "global_flag": "true",
        "headers": '{"Authorization":"Bearer {{token}}"}',
        "heading": "90",
        "horizontal_accuracy": "30",
        "hour": "9",
        "increment": "1",
        "index": "0",
        "is_anonymous": "false",
        "is_closed": "false",
        "is_personal": "true",
        "item_variable": "item",
        "json_string": '{"a":1}',
        "key": "uploaded_file",
        "keyboard": '{"active":"inline","inline":[[{"text":"Next","type":"callback","value":"next","next":"next_step"}]]}',
        "last_name": "Valiyev",
        "latitude": "41.311081",
        "length": "240",
        "limit": "10",
        "live_period": "60",
        "longitude": "69.240562",
        "loop_id": "movies_loop",
        "loop_mode": "range",
        "lua_code": "return true",
        "media_items": '[{"type":"photo","sourceType":"url","url":"https://example.com/1.jpg"}]',
        "message_id": "123",
        "message_id_source": "context",
        "message_type": "text",
        "method": "POST",
        "minute": "30",
        "month": "4",
        "open_period": "300",
        "operation": "set",
        "operator": "AND",
        "options": '["A","B"]',
        "output": "success",
        "params": '{"fields":["name","phone"]}',
        "parse_mode": "HTML",
        "phone_number": "+998901234567",
        "photo_file_id": "AgACAgQAAxkBA...",
        "photo_source_type": "url",
        "photo_url": "https://example.com/photo.jpg",
        "provider": "stripe",
        "proximity_alert_radius": "100",
        "question": "Qaysi javob to'g'ri?",
        "range_end": "10",
        "range_start": "1",
        "range_step": "1",
        "recipients": '{"mode":"current_chat"}',
        "response_variable": "api_response",
        "results": '[{"type":"article","title":"Result","messageText":"Hello"}]',
        "schedule": "0 9 * * *",
        "scheduled_date_time": "2026-04-21 09:30:00",
        "second": "0",
        "selected_callbacks": '["open_menu"]',
        "show_alert": "false",
        "skip": "0",
        "slug": "registration-form",
        "state": '{"key":"code","type":"text"}',
        "state_key": "code",
        "state_type": "text",
        "sticker_file_id": "CAACAgQAAxkBA...",
        "sticker_source_type": "file_id",
        "sticker_url": "https://example.com/sticker.webp",
        "store_headers": "true",
        "target_chat_ids": "[123456789]",
        "target_node_id": "welcome_message",
        "text": "Salom, {{user_first_name}}!",
        "time": "09:30:00",
        "timeout": "30",
        "timestamp": "1776754200",
        "title": "Office",
        "type": "quiz",
        "unpin_all": "true",
        "uploaded_file_uuid": "7c7c2f1e-0000-4000-9000-000000000000",
        "url": "https://api.example.com/items",
        "uuid": "7c7c2f1e-0000-4000-9000-000000000000",
        "v_card": "BEGIN:VCARD...",
        "value": "hello",
        "variable_name": "counter",
        "video_file_id": "BAACAgQAAxkBA...",
        "video_note_file_id": "DQACAgQAAxkBA...",
        "video_note_source_type": "url",
        "video_note_url": "https://example.com/video-note.mp4",
        "video_source_type": "url",
        "video_url": "https://example.com/video.mp4",
        "voice_file_id": "AwACAgQAAxkBA...",
        "voice_source_type": "url",
        "voice_url": "https://example.com/voice.ogg",
        "with_args": "true",
        "year": "2026",
    }
    return examples.get(name, '"value"')
