apiVersion: v1
kind: Secret
metadata:
  name: botmother-engine-secret
  namespace: botmother-engine
type: Opaque
stringData:
  BOT_TOKEN: "replace-me"
  RELEASE_BOT_TOKEN: ""
  API_URL: ""
  API_TOKEN: ""
  PROJECT_ID: "local"
  MONGO_ADDR: ""
  MONGO_DB_NAME: ""
  PLUGIN_API_KEY: "change-me"
  EXTERNAL_WEBHOOK_BASE_URL: ""
  REDIS_PASSWORD: ""
