apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentv2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BotSpace/agentv2.git
    targetRevision: main
    path: k8s/chart/agentv2
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: botmother
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
